// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.devicehub.client;

import com.google.devicehub.proto.DeviceRequest;
import com.google.devicehub.proto.DeviceResponse;
import com.google.devicehub.proto.DeviceType;
import com.google.devicehub.proto.Devices;
import io.grpc.ManagedChannel;

/**
 * Interface to provide instance and wrap around method for testing purpose, in the real
 * implementation the instance is generated by static method so it is not possible to mock directly.
 */
public interface HubConnectionProvider {
  ManagedChannel getManagedChannel(String host, int port);

  DeviceResponse sendDeviceRequest(ManagedChannel channel, DeviceRequest request);

  Devices getDevices(ManagedChannel channel, DeviceType deviceType);
}
